### ISSUE TITLE
TypeError: __init__() missing 14 required positional arguments:

### ISSUE THREAD

**Issue by xxrraa** [caillonantoine/RAVE#11]
Hey, thanks for this awesome release!  Trying to get some of the example script from the readme to work and having some trouble when loading pre-trained models.  

_**here's the specific code I'm running**_ 

import torch

torch.set_grad_enabled(False)
from rave import RAVE
from prior import Prior

import librosa as li
import soundfile as sf

################ LOADING PRETRAINED MODELS ################
rave = RAVE.load_from_checkpoint("./rave_pretrained/darbouka/prior.ckpt").eval()

_**here's the full error**_

`
Traceback (most recent call last):
  File "/Users/krayyy/PycharmProjects/pythonProject11/rave39test.py", line 11, in <module>
    rave = RAVE.load_from_checkpoint("./rave_pretrained/darbouka/prior.ckpt").eval()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pytorch_lightning/core/saving.py", line 153, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pytorch_lightning/core/saving.py", line 195, in _load_model_state
    model = cls(**_cls_kwargs)
TypeError: __init__() missing 14 required positional arguments: 'data_size', 'capacity', 'latent_size', 'ratios', 'bias', 'loud_stride', 'use_noise', 'noise_ratios', 'noise_bands', 'd_capacity', 'd_multiplier', 'd_n_layers', 'warmup', and 'mode'
`

**Thanks for your time**

**Comment by caillonantoine** [comment]
You're loading a prior checkpoint inside RAVE :)
