### ISSUE TITLE
training logs/loss curves

### ISSUE THREAD

**Issue by tals** [caillonantoine/RAVE#18]
Hey Antoine, love this work! Lots of clever tricks :)

Any chance you can share the training logs? I am trying to reproduce your findings (on a different dataset of similar difficulty), and these would be helpful to know if I am headed in the right direction.

For example, I ended up tweaking a few things (have more VRAM so I 4x the batch size and adjusted the LR by the sqrt of the bs ratio, as [proposed here](https://arxiv.org/abs/2006.09092)).

P.S: the distance metric sadly gets modified by the GAN feature matching loss. Maybe worth logging it separately - I almost had a heart attack haha when the distance metric started spiking :)

**Comment by caillonantoine** [comment]
Hi :) I agree, I'm gonna split the losses soon to make it clearer ! Maybe change a few labels too, and upload some usual training curves !

Thanks for the feedback !

**Comment by yeswecan** [comment]
@tals may I ask you what did you set the LR to in this case? I might try to do that too. I didn't get all through that paper you linked yet, though I appreciate you posting it.

**Comment by tals** [comment]
@yeswecan I was lazy and just did something like `np.sqrt(bs / original_bs) * original_lr` in the optimizer config function.

It might make sense to try running LR Finder on this. I imagine that the choice of dataset can also meaningfully affect the ideal LR

**Comment by tals** [comment]
btw @caillonantoine I refactored this code a bit on my branch: https://github.com/tals/RAVE/blob/daf5d059ae44df781d71f1a6b64462e2e6af5d4f/rave/model.py#L564

Having it on a separate function was convenient for LR finding :)

**Comment by tals** [comment]
have you ever seen the feat_loss stabilize? It seems to be always increasing for me (see graphs below), where as D's loss seems to stabilize.

Interestingly enough, the model seems to sound pretty decent, despite the large increase in STFT distance, even on a challenging data set like vocal singing.
Before D kicked in, the audio was robotic (which makes sense due to lack of phase info), and D clears it out a lot as expected :)

Also, have you tried training the entire thing together, or did this make G just get bullied around by D?

![image](https://user-images.githubusercontent.com/761863/147511323-7836de70-97c9-40c2-953e-30c7a76598db.png)
