### ISSUE TITLE
Checkpoint file missing

### ISSUE THREAD

**Issue by harin-git** [caillonantoine/RAVE#19]
Hi,

I trained the model and exported following the instructions and it created the `ts` file.
Now I want to load the model from checkpoint but I can't find the `checkpoint.ckpt` anywhere in the directory.
For each versions of the run there is a checkpoint folder but they are empty.

Am I missing something really silly here? Could it be that my training wasn't long enough (half a day)?

Sorry if this is a nooby question!

**Comment by caillonantoine** [comment]
Checkpoints are saved approximately each 10k steps, are you sure you have been training RAVE long enough?
