### ISSUE TITLE
Discriminator training

### ISSUE THREAD

**Issue by tals** [caillonantoine/RAVE#21]
Hey Antoine,

I've attempted to train RAVE on a ~200h guitar dataset, trained for 2.5M steps on bs of 32.
The results so far appear weaker than expected (top is GT, bottom is reconstruction)
![image](https://user-images.githubusercontent.com/761863/148170915-d565efc6-f5be-4cfe-8827-b7ec05442bf5.png)

Looking more closely at the situation, we see a few things:
- the distance took a significant hit when D was introduced, and never recovered (13 -> 15).
- While the distance metric converged, the feature distance keeps increasing. This seems like some unhealthy situation between the two. Will try tapering off LR and some other GAN tricks to help there.
- There is some suspicious looking situation in the latent codes - the informative part keeps oscillating.
![image](https://user-images.githubusercontent.com/761863/148171554-f3113af8-9b94-4f2f-9cd9-82e6648a3280.png)

Did you observe the same situation with D in your runs?

**Comment by caillonantoine** [comment]
Hi,

> the distance took a significant hit when D was introduced, and never recovered (13 -> 15).

This usually happens, and should not impact quality that much !

> While the distance metric converged, the feature distance keeps increasing. This seems like some unhealthy situation between the two. Will try tapering off LR and some other GAN tricks to help there.

It actually behave exactly like the melGAN model, so I'm not sure this is a sign of unbalanced training! 

> There is some suspicious looking situation in the latent codes - the informative part keeps oscillating.

That looks pretty weird indeed ! I guess it is because the model has failed to converge during stage 1.

Maybe the dataset is too complex, I'm currently working on training strategies to make RAVE converge better on complex dataset, but it could explain why the end result is not satisfactory ! I'll keep you updated.

By the way, what are you using to display losses ? I don't recognize tensorboard, and I think stacking the different estimated dimensionality makes a lot of sense !

**Comment by tals** [comment]
> It actually behave exactly like the melGAN model, so I'm not sure this is a sign of unbalanced training!

Ha weird. I am not convinced this is healthy, though. I imagine this would also bottleneck model performance, since it needs to allocate its learning budget chasing this thing while not making progress elsewhere.

> That looks pretty weird indeed ! I guess it is because the model has failed to converge during stage 1.

It seems pretty converged to with respect to distance. How can you tell it didn't converge?

It is possible the dataset is too complex and the model should be scaled up a bit, but the dynamics with D seem suspicious to me.

I am using [w&b](https://wandb.ai/). I've added code to send metrics + compressed AAC samples to it in [n my fork](https://github.com/tals/RAVE/blob/master/rave/audio_logger.py).
In general it works pretty well, especially relative to tensorboard, but it does have its own sharp edges and annoyances :)

**Comment by caillonantoine** [comment]
maybe regularizing the discriminator would prevent this loss from explosion ! I am investigating it :)

**Comment by tals** [comment]
@caillonantoine did you figure out a fix? :)

**Comment by caillonantoine** [comment]
I've applied weightnorm to the discriminator layers, and it has reduced the behavior a bit ! However I'm still not sure this was an issue in the first place, so I'm not working on it anymore ! :)
