### ISSUE TITLE
Batch size effect on convergence and final sound quality

### ISSUE THREAD

**Issue by moiseshorta** [caillonantoine/RAVE#22]
Hi Antoine,

This is not an issue, but rather an insight from training RAVE on diverse datasets.

I've been thoroughly training RAVE with some diverse datasets, ranging from single instrument to full music tracks.

One thing I've noticed is that when I train the 'full music tracks' the elements which account for more harmonic and melodic content have a hard time getting modeled by RAVE. Whereas the more rhythmic features have no problem cutting through.

So far I've been training with a `batch size = 64`, which is 8 times more than the default value of 8. 

I'm wondering if this has any effect on the convergence, and thus, the overall quality of the final model?.
 Would retraining 'full track music' models with the default batch size alter the convergence and subsequent quality of the sound? 

Have you had any insights of this issue?

Thanks again, can't wait for the realtime plugins for MAX/Pd to drop!

**Comment by yeswecan** [comment]
@moiseshorta thanks for sharing your observations!

I wonder how can you comment on the relation of the batch size to sound quality? How did you pick that particular batch size?

**Comment by yeswecan** [comment]
Also I wonder if there's any data on the effect that the internal representation size has on the quality?

**Comment by moiseshorta** [comment]
> @moiseshorta thanks for sharing your observations!
> 
> I wonder how can you comment on the relation of the batch size to sound quality? How did you pick that particular batch size?

Hi,

I might add that this is mostly intuition upon seeing a small article on how sometimes smaller batch size leads to better convergence, hence my thought would be that some features 'cut through' when you remain in a lower batch size; again, this is a personal intuition and need to explore further.

The `batch size = 64` comes from wanting to fill the whole GPU memory while training; I've been training on a GTX 3090 so far.

**Comment by caillonantoine** [comment]
Hi :) That's a good question, and I have no "real" answer to it, except that I have been experimenting with smaller / higher batch sizes and 8 was the best option when considering training speed / convergence stability !

Concerning the convergence problem, I'm currently working on it ! RAVE can now be trained using a cyclical schedule for the regularization term, allowing easier convergence during the first training stage. I'm also experimenting with lighter regularization and manually defined latent size to help the model fit complex dataset !

By the way the max/msp + Pd externals are available here https://github.com/acids-ircam/nn_tilde ! And the code to export real-time model will drop very soon now, I promise ;)

Cheers !
