### ISSUE TITLE
Merge RAVE models

### ISSUE THREAD

**Issue by jeanbrazeau** [caillonantoine/RAVE#26]
Hello Antoine,
Is it possible to merge or combine multiple RAVE models together? Thanks!

**Comment by caillonantoine** [comment]
Hi ! I'm not sure what you want to achieve, what would the attribute of a "merged" model be ?

**Comment by caillonantoine** [comment]
When you say output, you mean a pretrained model ?

**Comment by caillonantoine** [comment]
Then you can't really "merge" the different models, since they are in essence very different functions !
