### ISSUE TITLE
AssertionError when attempting to run train_rave.py

### ISSUE THREAD

**Issue by moiseshorta** [caillonantoine/RAVE#4]
Hi,

I'm currently attempting to train using the provided cli_helper.py script.

Unfortunately, I seem to come up with this error whenever I actually attempt to run `train_rave.py`

```
Traceback (most recent call last):
  File "/home/hexorcismos/Desktop/AI/RAVE/train_rave.py", line 109, in <module>
    assert len(CUDA)
AssertionError
```

A quick fix that made it work is to comment out these lines in `train_rave.py`.
```
    CUDA = gpu.getAvailable(maxMemory=.05)
    assert len(CUDA)
    environ["CUDA_VISIBLE_DEVICES"] = str(CUDA[0])
```
Then it would detect my GPU card with no problems.

Wanted to bring it up to attention for anybody experiencing the same error.

Best and thanks for open sourcing this exciting paper!

**Comment by caillonantoine** [comment]
That is weird ... What kind of GPU do you have ?

**Comment by moiseshorta** [comment]
@caillonantoine Training on a GTX 1060

**Comment by caillonantoine** [comment]
I think that's because there is a small amount of memory used by the x server. I'll will fix this issue soon

**Comment by caillonantoine** [comment]
I've changed the way GPU are discovered in 99a2c5269fed1611dd7d374b848fccd302d3bf30, can you try and tell me if it did fix the issue ? Thanks

**Comment by moiseshorta** [comment]
@caillonantoine Just tried training with the tix and it solved the issue.
