### ISSUE TITLE
What's the correct order of the two training steps?

### ISSUE THREAD

**Issue by Cortexelus** [caillonantoine/RAVE#5]
The paper says
- Step 1: `Representation learning` (VAE)
- Step 2 `Adversarial fine-tuning` (fine-tuning the VAE decoder like a GAN)

But `cli_helper.py` first trains `RAVE` then the `prior`. The `RAVE` model contains a discriminator, i thought this was Step 2.

Thanks for clarifying my confusion!

**Comment by caillonantoine** [comment]
Hi, sorry for the confusion! 

Both stage for rave are included in the `train_rave` script, if you did not change the number of iteration in the `cli_helper` the adversarial stage will kick in at 1M steps!
