### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by xxrraa** [caillonantoine/RAVE#6]
Hello, I apologize if this is the wrong place to post this, it is not an issue with the code.

I wanted to know if there are any pre-trained models anyone can lend me as I don't have a GPU to train :( 

Thanks for your time

**Comment by JelaniThompson** [comment]
I'm having the same issue unfortunately. Great work though, this is some really cutting edge stuff 👍🏾

**Comment by caillonantoine** [comment]
I will post a few pretrained models this week (voice, percussion, music)!

**Comment by xxrraa** [comment]
Greatly appreciate the response and am looking forward to tht.  Thanks so much!
