### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by coice** [caillonantoine/RAVE#8]
Though not exactly the same, how would you compare the audio quality of RAVE compared to MELGan or HIFIGan?

Would you say RAVE is better, about the same, or worse?

(I'd love to test it myself, but there are no pre-trained models currently available and I don't have the GPU resources to train from scratch!)

Thank you for your time.

**Comment by caillonantoine** [comment]
Hi,

It's hard to compare models that are not built to address the same task (representation learning for RAVE, mel inversion for melGAN and HIFIGAN).

RAVE is however faster than the other models to train and generate while operating on a higher sampling rate (48kHz vs 22kHz). When comparing melGAN to RAVE on 48kHz signals, RAVE has less artifacts thanks to its multi-band decomposition!

**Comment by coice** [comment]
This was very helpful, thank you!
